[package]
name = "ipfs-stream-deadlock"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.0", features = ["full"] }
futures = "0.3.31"
rust-ipfs = { version = "0.12.2", features = ["experimental_stream"] }
anyhow = "1.0.91"
rand = "0.8.5"